### ISSUE TITLE
[BUG]: ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by Woisek** [LEv145/--sd-webui-ar-plus#23]
Out of nowhere, suddenly, the extension throws an error and  compromises a frozen A1111 v1.7.0 installation and an up to date v1.9.0. It worked flawlessly so far and I used it daily and in every session I do.
Please take a look on this.

*** Error calling: V:\AI_programms\stable-diffusion-webui\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py/ui
    Traceback (most recent call last):
      File "V:\AI_programms\stable-diffusion-webui\modules\scripts.py", line 489, in wrap_call
        return func(*args, **kwargs)
      File "V:\AI_programms\stable-diffusion-webui\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 282, in ui
        self.read_resolutions()
      File "V:\AI_programms\stable-diffusion-webui\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 228, in read_resolutions
        self.res_labels, res, self.res_comments = parse_resolutions_file(
      File "V:\AI_programms\stable-diffusion-webui\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 116, in parse_resolutions_file
        label, width, height = line.strip().split(",")
    ValueError: not enough values to unpack (expected 3, got 2)

---

Thanks for your efforts.

**Comment by Woisek** [comment]
Found out that a preset for resolutions missed a comma. It's working again.
